FastCampusGroup6/ToyProject__Nintendo

src/components/common/UserHeader/index.tsx, src/layouts/MypageLayout.tsx, tsconfig.json
ㅔ헤헤ㅔ헤헤...
user headr 컴포넌트 날라가버렸네유... ㅠㅠ
=>  fix :  PR충돌 수정2

src/pages/access/ageSignUp/index.module.scss, src/pages/access/index.module.scss, src/pages/access/logIn/index.module.scss, src/pages/access/logIn/index.tsx, src/pages/access/logOut/index.module.scss, src/pages/access/passwordChangeForm/index.module.scss, src/pages/access/passwordCheck/index.module.scss, src/pages/access/signUpForm/index.module.scss, src/pages/access/signUpForm/index.tsx
SignUp Page css에 문제가 있어 수정하고 로그인기능 임시로 추가하였습니다.
전역으로 사용되는 css 내용전부 삭제하였습니다.
=> 65 signup page html css 수정 및 로그인기능추가

src/components/payment/payMethod/BankConnect.module.scss, src/components/payment/payMethod/BankConnect.tsx, src/components/payment/payMethod/ConnectedBank.module.scss, src/components/payment/payMethod/ConnectedBank.tsx, src/components/payment/payMethod/PossibleBank.tsx, src/pages/payment/payMethod/index.module.scss, src/pages/payment/payMethod/index.tsx
root/payment/:username/payMethod 에 위치한 라우터 스타일 구현완료
전체 스타일 완성
계좌 조회, 간편결제 버튼 클릭 시 각각 나오는 콜랩스와 모달 창도 스타일 완성했습니다.
=> 26 paymethod 페이지 html css 구현

src/components/maypage/GetItem.module.scss, src/components/maypage/GetList.module.scss, src/components/maypage/JjimItem.module.scss, src/components/maypage/JjimList.module.scss, src/components/maypage/Nav.module.scss, src/pages/mypage/certProfile/editProfile/index.module.scss, src/pages/mypage/certProfile/editProfile/index.tsx, src/pages/mypage/certProfile/index.module.scss, src/pages/mypage/certProfile/index.tsx, src/pages/mypage/index.module.scss
edit / cert Profile page HTML / CSS 구조 구현
=> 63 certedit profile page htmlcss 구현

src/pages/access/logOut/index.module.scss, src/pages/access/logOut/index.tsx
=> 48-logout-page-로그아웃기능추가

src/pages/access/passwordCheck/index.module.scss, src/pages/access/passwordCheck/index.tsx
=> 59-passwordcheck-page-기능구현

package-lock.json, package.json, public/images/React App_files/bundle.js.다운로드, public/images/search/search_icon.svg, src/components/home/HomeSwiper/index.tsx, src/components/search/Filter/index.module.scss, src/components/search/Filter/index.tsx, src/components/search/Genre/index.module.scss, src/components/search/Genre/index.tsx, src/components/search/ProductList/index.tsx, src/components/search/SearchBar/index.module.scss, src/components/search/SearchBar/index.tsx, src/index.tsx, src/pages/search/index.tsx, src/recoil/search/productState.ts, src/recoil/search/queryStringState.ts, src/utils/search.ts
1. recoil을 사용해서 검색 필터 상태를 관리하는 로직을 추가했습니다. 
- recoil/search/productState.ts 
- queryStringState.ts 
2. /search 페이지 검색 필터 기능 html, css를 구현했습니다. 
- component/search폴더를 참고해주세요. 
- pages/search.tsx를 참고해주세요. 
3. generateQueryString함수를 만들었습니다. 
- URLSearchParams API를 사용해서 컴색 쿼리 객체를 문자열로 만들어주는 기능입니다. 
- /utils/search.ts를 참고해주세요.
=> 22 search filter 기능 추가

src/pages/access/passwordCheck/index.tsx, src/pages/access/signUpForm/index.module.scss, src/pages/access/signUpForm/index.tsx
**중복체크기능 구현**
중복체크기능을 구현하였고 더미데이터로 중복체크기능을 확인할 수 있습니다. ( const dummyData = ['John', 'Jane', 'Alice'])  아직 완성되지않아 수정이 필요합니다. 수정필요사항 :(닉네임 메세지와 중복체크 메세지가 모든상황에 적절하게 나오지는 않아 수정필요합니다.)
**체크박스**
체크박스를 눌러야 가입버튼이 활성화됩니다 (체크박스 버튼클릭 후  css수정필요)
**이미지 미리보기 및 업로드 기능구현**
이미지를 올리면 미리보기 및 상태에 저장됩니다.
=> 로그인 페이지 기능구현

src/components/payment/CartItem.tsx, src/components/payment/PayProcessFlow.tsx, src/components/payment/ShoppingCart.tsx, src/pages/payment/checkInfo/index.tsx
1. '@/components/payment/PayProcessFlow.tsx' 컴포넌트에 정규식 범위에 오류가 있어 장바구니에 계속 빨간칠이 되어있었는데, 모르고 있다 발견해서 수정했습니다.
2. '@/components/payment/CartItem.tsx', '@/components/payment/ShoppingCart.tsx' 의 기존 출력 문구를 그냥 아무거나로 했었는데, 더미데이터에 연결했습니다. 로그인기능 연동되면 recoil로 user데이터 받아서 수정하면 될것같아요.
3. 추가로 가격 표기에 toLocalString() 메서드를 사용해 천 단위마다 콤마를 알아서 찍어주게 했습니다. 이런 메서드도있네요
=> 38 checkinfo page feature

src/pages/payment/dummyGoods2.json, src/pages/payment/dummyTransactionDetails.json, src/pages/payment/orderComplete/index.module.scss, src/pages/payment/orderComplete/index.tsx
+ 더미데이터로 주문번호(api 전체거래내역의 detailId), 제품명 받아오기
+ localStorage의 'cart'내용 초기화(랜딩 시)
=> ✨ feat : orderComplete페이지 더미 데이터 연결, 장바구니 목록 삭제 기능

src/App.tsx, src/components/common/UserHeader/index.tsx, src/components/payment/Loading.module.scss, src/components/payment/Loading.tsx, src/components/payment/PayProcessFlow.module.scss, src/components/payment/payMethod/BankConnect.tsx, src/pages/payment/orderComplete/index.tsx, src/pages/payment/payMethod/index.tsx
api 호출 시 비동기 통신 하는 동안 작동하는 컴포넌트를 추가했습니다.
https://github.com/FastCampusGroup6/ToyProject__Nintendo/assets/84277185/21b4458c-09ff-4aca-b5d9-f323b1ad52b2
Loading 컴포넌트는 props로 color를 받으며 사용 할 때
`<Loading color='원하는 색깔코드' />` 를 넣으면 동작합니다.
'@/components/payment/Loading.tsx' 참고하시면 됩니다!
=> 115 payment loading

src/components/common/UserHeader/index.tsx, src/components/payment/ShoppingCart.tsx, src/pages/payment/checkInfo/index.tsx, src/pages/payment/index.tsx, src/pages/payment/payMethod/index.tsx, src/recoil/common/matchedUserCartState.ts
recoil에 matchedUserCart를 추가하여 해당 오류들 픽스했습니다. 일단 실험해봤는데 말씀주셨던 문제상황은 발견하지 못했습니다. 혹시 있으면 바로 말씀해주세요ㅠㅠ
=> :bug: fix : 유저헤더 장바구니 개수 오류, shoppingCart 총합 오류 수정

src/components/payment/ShoppingCart.tsx
닉네임이 한글이면 encode문제인듯.. 사실 잘 모르겠네요. 어쨌든 제대로 동작 하는거 같습니다.
=> :bug: fix : totalPrice 제대로 출력안되는 오류

src/components/access/validate/index.tsx, src/pages/access/logOut/index.module.scss, src/pages/access/logOut/index.tsx, src/pages/access/signUpForm/index.module.scss, src/pages/access/signUpForm/index.tsx
=> fix html,css수정

src/pages/mypage/certProfile/editProfile/index.module.scss, src/pages/mypage/certProfile/editProfile/index.tsx, src/pages/mypage/index.tsx
개인정보 수정 페이지에 submit버튼 조건 추가 했습니다. 
* 비밀번호 이중확인 틀릴 시 => 서브밋 불가
* 닉네임 입력시 에러 메세지 뜨는 상황에서는 서브밋 불가하도록 수정 예정
** 창휘님이 말씀하신 API상 등록된 계정 조회 기능도 시간적 여유가 되면🥹 수정해 두도록 하겠습니다!
=>  fix : submit 조건추가

src/components/common/MainHeader/index.tsx, src/components/common/UserHeader/index.tsx, src/pages/access/ageSignUp/index.tsx, src/pages/access/index.tsx, src/pages/access/logIn/index.tsx, src/pages/access/logOut/index.tsx
=> 리팩토링: a태그 link로 수정 및 hook을 이용해 로그아웃페이지 수정

src/pages/payment/dummyAccounts.json, src/pages/payment/dummyAccountsList.json, src/pages/payment/dummyGoods1.json, src/pages/payment/dummyGoods2.json, src/pages/payment/dummyOrder.json, src/pages/payment/dummyTransactionDetails.json, src/pages/payment/dummyUser.json, src/pages/payment/dummyVerifiedUser.json
This reverts commit d10e562323ef77e6cf8beb7f2c127bd480c19892.
더미데이터 삭제한거 되돌렸습니다
=> Revert "🗑️ refactor : 기존 dummyData 삭제"

src/apis/payment/account/index.ts, src/components/common/MainHeader/index.tsx, src/components/mypage/bank/BankSelect.tsx, src/components/mypage/nav/Nav.tsx, src/components/mypage/productList/GetList.tsx, src/components/search/Filter/index.module.scss, src/components/search/Filter/index.tsx, src/pages/mypage/account/addAccount/index.tsx, src/pages/mypage/account/index.tsx, src/pages/mypage/index.tsx
- mypage url 고정값 수정
- mypage/account, myapge/account/add redirect 기능 추가
- mypage/account, myapge/account/add  try catch문 API로 이동
- search 페이지 style을 수정했습니다.
- mainHeader에서 마이 페이지로 가는 주소를 변경했습니다.
=> refactor : mypage redirect 기능 및 라우터 주소 변경

src/pages/access/ageSignUp/index.module.scss, src/pages/access/index.module.scss, src/pages/access/logIn/index.module.scss, src/pages/access/logIn/index.tsx, src/pages/access/logOut/index.module.scss, src/pages/access/passwordChangeForm/index.module.scss, src/pages/access/passwordCheck/index.module.scss, src/pages/access/signUpForm/index.module.scss, src/pages/access/signUpForm/index.tsx
scss수정이 필요하여 access에 들어가는 모든 페이지 수정하였습니다. 현재 헤더부분과 메인부분의 간격이 너무 벌어져 전부 수정하였고 예시 하나를 가져왔습니다.
기존scss
변경 scss
=> 로그인 및 회원가입scss 전체수정

src/apis/user/editedUserInfo/index.ts, src/components/mypage/productList/GetItem.module.scss, src/components/mypage/productList/GetItemMore.module.scss, src/components/mypage/productList/GetList.module.scss, src/components/mypage/productList/GetList.tsx, src/pages/access/signUpForm/index.module.scss, src/pages/access/signUpForm/index.tsx, src/pages/mypage/certProfile/editProfile/index.tsx, src/pages/mypage/certProfile/index.tsx, src/pages/mypage/getItemAll/index.module.scss, src/pages/mypage/getItemAll/index.tsx, src/pages/mypage/index.tsx, src/types/user.ts
- 개인정보 수정 페이지  :비밀번호 API 연동 오류 수정
-  구매내역 페이지 :  구매내역 비어있을때 오류나는 부분 수정
=> 146 refactor edit profile page넥네임 비번 미반영 에러

src/components/mypage/productList/GetItem.tsx, src/components/mypage/productList/GetItemMore.module.scss, src/components/mypage/productList/GetItemMore.tsx, src/components/mypage/productList/GetList.module.scss, src/components/mypage/productList/GetList.tsx, src/pages/mypage/certProfile/index.tsx, src/pages/mypage/getItemAll/index.tsx
김성은 최종 커밋
-업데이트 내용 :  구매내역 최신순으로 나열되도록 수정 
(마이페이지 / 마이페이지>전체 구매내역 조회)
=> 162 구매내역 조회 최신순으로 정렬

README.md
=> main to release pr

README.md
=> 링크 또 수정 또pr

README.md
=> 또 readme 누락된거 업데[이트
